.travis.yml, bin/build.sh, config.json, exercises/hello-world/hello_world.example, exercises/hello-world/hello_world_tests.plt
This seems to work ok. I copied the same build script we used in xElm. 
Here is a running build https://travis-ci.org/parkerl/xprolog/jobs/164838544
Edit: This is all green and the exercise is complete. 
(P.S. Hope I'm not jumping in when someone else is already on top of this.)
=> Add hello_world with Travis CI  and build.sh

exercises/leap/leap.example, exercises/leap/leap.pl, exercises/leap/leap_tests.plt
@qjd2413 here are some style changes I'd like to suggest based on "leap". Let's use this PR to discuss.
=> Updates leap with suggested style changes

docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
Feel free to give me suggestions on any of these, I can't really find too many resources or information (which is odd-- given it is almost 45 years old)
=> Documentation

exercises/anagram/anagram_tests.plt, exercises/binary/binary_tests.plt, exercises/grains/grains_tests.plt, exercises/hamming/hamming_tests.plt, exercises/hello-world/hello_world.pl, exercises/hello-world/hello_world_tests.plt, exercises/leap/leap.pl, exercises/leap/leap_tests.plt, exercises/nucleotide-count/nucleotide_count_tests.plt, exercises/rna-transcription/rna_transcription_tests.plt, exercises/space-age/space_age_tests.plt, exercises/sum-of-multiples/sum_of_multiples_tests.plt, exercises/triangle/triangle_tests.plt
All tests updated with skipping
First test fails for each
First test has `condition(true)` so that it is not skipped
Closes #18 
Closes #13
=> Add more verbose test skipping

docs/TESTS.md
Correcting a typo in the documentation for tests.
=> Update TESTS.md - typo in docco

exercises/hello-world/hello_world_tests.plt
=> typos in test

config.json, exercises/queen-attack/README.md, exercises/queen-attack/queen_attack.example, exercises/queen-attack/queen_attack.pl, exercises/queen-attack/queen_attack_tests.plt
So little amount of implemented exercises on Prolog, I want to help.
=> Implementing: queen-attack

docs/LEARNING.md
I found this site really helpful when starting in Prolog
=> P-99 Added.

exercises/hello-world/README.md
In the README the string "Hello, World!" has a comma, but it's not what the program is testing for. Removed the comma.
=> Hello world should have no comma

config.json, exercises/pascals-triangle/README.md, exercises/pascals-triangle/pascals_triangle.example, exercises/pascals-triangle/pascals_triangle.pl, exercises/pascals-triangle/pascals_triangle_tests.plt
@parkerl  I think is ok, but if you find some free time have a look at this to be sure.
=> add pascals-triangle

exercises/hello-world/hello_world.pl, exercises/hello-world/hello_world_tests.plt, exercises/queen-attack/queen_attack.pl, exercises/queen-attack/queen_attack_tests.plt
=> Fixed broken links

exercises/hello-world/hello_world.example, exercises/hello-world/hello_world_tests.plt
=> simplify hellow world (prolog)

bin/fetch-configlet
Updates fetch-configlet to use github token.
=> update fetch configlet

config/maintainers.json
Hey y'll, I'm looking to help get the prolog track working for v3.  Would that be alright to help contribute?
=> Add neenjaw to maintainers.json

exercises/practice/anagram/.meta/config.json, exercises/practice/binary/.meta/config.json, exercises/practice/complex-numbers/.meta/config.json, exercises/practice/dominoes/.meta/config.json, exercises/practice/grains/.meta/config.json, exercises/practice/hamming/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/isogram/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/nucleotide-count/.meta/config.json, exercises/practice/pascals-triangle/.meta/config.json, exercises/practice/queen-attack/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/satellite/.meta/config.json, exercises/practice/space-age/.meta/config.json, exercises/practice/spiral-matrix/.meta/config.json, exercises/practice/sum-of-multiples/.meta/config.json, exercises/practice/triangle/.meta/config.json, exercises/practice/wordy/.meta/config.json
To help tracks define the files in the exercise's `.meta/config.json` file, we've added support for defining these file patterns in the track's `config.json` file. See [this PR](https://github.com/exercism/docs/pull/58).
This PR updates the file paths defined in the `files` property of each exercise's `.meta/config.json` file according to the file patterns defined in the track's `config.json` file.
We only update a file path in the `.meta/config.json` file if:
- The file path pattern is a non-empty array in the `config.json` file
- The file path pattern is either not set or an empty array in the `.meta/config.json` file
This means that exercises that had already defined files in the `.meta/config.json` won't be touched in this PR.
Note that this PR is just an easy way for tracks to …
=> 🤖 Sync exercise files keys based on file path patterns

config.json, exercises/practice/complex-numbers/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/nucleotide-count/.meta/config.json, exercises/practice/pascals-triangle/.meta/config.json, exercises/practice/queen-attack/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/space-age/.meta/config.json, exercises/practice/spiral-matrix/.meta/config.json, exercises/practice/sum-of-multiples/.meta/config.json
Really sorry about this. I accidentally used the wrong pattern in a previous PR.
=> Fix file patterns

exercises/practice/triangle/.docs/instructions.md
Described in more detail in #130, this makes the instructions match the tests.
I think a nondeterministic solution could be more fun, but this is the third exercise in the track. I think nondeterminism is where Prolog really shines, but maybe better to save for later exercises?
=> Make instructions for ioscelese match tests

exercises/practice/hello-world/hello_world.pl
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

exercises/practice/queen-attack/queen_attack.pl
=> Provide better defaults for the queen_attack solution

exercises/practice/queen-attack/queen_attack.pl
=> Changed example dimensions of create

exercises/practice/collatz-conjecture/collatz_conjecture_tests.plt
See https://github.com/exercism/prolog/issues/81
=> collatz-conjecture: fix tests

exercises/practice/nucleotide-count/nucleotide_count_tests.plt
See https://github.com/exercism/prolog/issues/81
=> nucleotide-count: fix tests

exercises/practice/rna-transcription/rna_transcription_tests.plt
See https://github.com/exercism/prolog/issues/81
=> rna-transcription: fix tests

exercises/practice/sum-of-multiples/.meta/sum_of_multiples.example.pl, exercises/practice/sum-of-multiples/sum_of_multiples_tests.plt
This actually caught an error in the example implementation (guess it's working).
See https://github.com/exercism/prolog/issues/81
=> sum-of-multiples: fix tests

bin/add-exercise
Just a little tool to help with setup up some new exercise boilerplate
=> scripts: add script to add exercise

config.json, exercises/practice/reverse-string/.docs/instructions.md, exercises/practice/reverse-string/.meta/config.json, exercises/practice/reverse-string/.meta/reverse_string.example.pl, exercises/practice/reverse-string/.meta/tests.toml, exercises/practice/reverse-string/reverse_string.pl, exercises/practice/reverse-string/reverse_string_tests.plt
- reverse-string: add exercise
- reverse-string: add exercise
=> reverse-string: add exercise

exercises/practice/change/.meta/change.example.pl, exercises/practice/change/.meta/config.json
Closes https://github.com/exercism/prolog/issues/218
=> change: speedup

config.json, exercises/practice/matching-brackets/.docs/instructions.md, exercises/practice/matching-brackets/.meta/config.json, exercises/practice/matching-brackets/.meta/matching_brackets.example.pl, exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/matching_brackets.pl, exercises/practice/matching-brackets/matching_brackets_tests.plt
- **Add matching brackets**
- **Add `matching-brackets` exercise**
=> Add `matching-brackets` exercise

config.json, exercises/practice/clock/.docs/instructions.md, exercises/practice/clock/.meta/clock.example.pl, exercises/practice/clock/.meta/config.json, exercises/practice/clock/.meta/tests.toml, exercises/practice/clock/clock.pl, exercises/practice/clock/clock_tests.plt
- **Add `clock` exercise**
- **Add `clock` exercise**
=> Add `clock` exercise

exercises/practice/wedding-woes/wedding_woes.pl
The line should read "likes", as per the topic of the exercise.
=> Fixing typo

config.json, exercises/practice/flower-field/.docs/instructions.md, exercises/practice/flower-field/.docs/introduction.md, exercises/practice/flower-field/.meta/config.json, exercises/practice/flower-field/.meta/flower_field.example.pl, exercises/practice/flower-field/.meta/tests.toml, exercises/practice/flower-field/flower_field.pl, exercises/practice/flower-field/flower_field_tests.plt
This PR adds Flower Field, deprecating Minesweeper. See https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967
=> Add `flower-field`, deprecating `minesweeper`
